language: node_js
node_js:
  - "stable"
jobs:
  include:
    - stage: build
      script: yarn build
    - stage: test
      script: yarn test
    - stage: release
      script: yarn release

cache: yarn