language: node_js
node_js:
- stable
dist: xenial
os: linux
jobs:
  include:
  - stage: build
    script: yarn build
  - stage: test
    script: yarn test
  - stage: deploy
    deploy:
      provider: npm
      email: m.zakria90@gmail.com
      api_token:
        secure: n94UlOHPowBSp/5Yg0wH3rEm1HVr1nRFo04L1kEu1Xtm2+52uUrMsYRjUZBuZrbj6AdnciDLsTkisS+y7YDAVPChrOTjn2DbKgrUq650S3fcpRA7ZNvpgq9kID4Pf9G6dV5zDXOW5uuh1KPi0ZpBF3T7jzpHRUWfRM3KC1O0AV1BezuASUfNimfvecmdTCX8qyd1190knRR4RD25Q4yYEq2LUk+j74D0IpY4G/g5/E73F3kWZmgt254o8cKWwNOKl0RLsUtjHqoOHUX07UpDXFl7qv9BcEfpAIFSNf+2muM0RVcFUX8wXaxYxnuXAx6hpvVCfkomnaysx3ml4fnwYHl4zjfJ4XSSR8PrJJAVcmU5rFLMkavZRMO1GI9PHfgd1IG37jUqvF1JpM2EF475HNjIR3rJRDwiAksbtThjQcbCUQ0E/MqCUNlT1C6lTN7VDtm+3Wbv68pGK240L/jgCRwgSr/C18+p/8U58B8TIdE2bJAyIGZ6Ihhq2+qw1T/pIU24WSAGNs8n+5KsD40IjqWkRr07khjcPFWIeZC/P9EtP3UvENhVukKxuvHRoV+GQB2s8QJeVB8Z+Wo2UvmpMTg2zLtMjnUOYrB7ZW6E8P6oAJjJWyNwWKHEt5ReSiFX7CZh/hoVlKVpYvXHODibsZ5bkEpYsMYb34BWgcXx+HA=
      cleanup: true
      on:
        branch: master
        repo: mahmoudZakaria90/vue-currency-directive
cache: yarn
